### ISSUE TITLE
send OI param for historical data API

### ISSUE THREAD

**Issue by vividvilla** [zerodha/phpkiteconnect#11]

**Comment by VarunAgw** [comment]
PHP SDK is dead and no one is maintaining it anymore

**Comment by vividvilla** [comment]
@ranjanrak can you take a look at this?

**Comment by ranjanrak** [comment]
@vividvilla  Ahh, didn't receive any alert for this tag. Saw this now. Have fixed this issue(missing oi field in historical data response) and raised an PR [here](https://github.com/zerodha/phpkiteconnect/pull/12/commits/f71cba86389ed01d135e7d338e3408395aec6c14). Please review this.

**Comment by ranjanrak** [comment]
@VarunAgw 
This is already fixed through [this PR](https://github.com/zerodha/phpkiteconnect/pull/12).
